/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Class2 */

#ifndef _Included_Class2
#define _Included_Class2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Class2
 * Method:    invokeAPrivate
 * Signature: (LClass1;)V
 */
JNIEXPORT void JNICALL Java_Class2_invokeAPrivate
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
