/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Class1 */

#ifndef _Included_Class1
#define _Included_Class1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Class1
 * Method:    invokeAPrivate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Class1_invokeAPrivate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
