/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JCar */

#ifndef _Included_JCar
#define _Included_JCar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JCar
 * Method:    nativeNew
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_JCar_nativeNew
  (JNIEnv *, jobject, jint);

/*
 * Class:     JCar
 * Method:    getMileage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JCar_getMileage
  (JNIEnv *, jobject);

/*
 * Class:     JCar
 * Method:    driveRandom
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JCar_driveRandom
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
