/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloJNIWorld */

#ifndef _Included_HelloJNIWorld
#define _Included_HelloJNIWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloJNIWorld
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloJNIWorld_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
