/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FieldAccess */

#ifndef _Included_FieldAccess
#define _Included_FieldAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FieldAccess
 * Method:    getAPrivate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_FieldAccess_getAPrivate
  (JNIEnv *, jobject);

/*
 * Class:     FieldAccess
 * Method:    setAPrivate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_FieldAccess_setAPrivate
  (JNIEnv *, jobject, jint);

/*
 * Class:     FieldAccess
 * Method:    setAStaticPrivate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_FieldAccess_setAStaticPrivate
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
